title: grimoire.jamppa.it
description: A site to save some useful stuff
theme: just-the-docs

url: https://grimoire.jamppa.it

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
